#!/usr/bin/env python2.7
# Copyright 2016 Arjun Arkal Rao
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Author : Arjun Arkal Rao
Affiliation : UCSC BME, UCSC Genomics Institute
File : protect/test/test_transgene.py
"""
from __future__ import print_function

from protect.common import untargz
from protect.mutation_translation import run_transgene
from protect.pipeline.ProTECT import _parse_config_file
from protect.test import ProtectTest
from toil.job import Job

import os
import subprocess


class TestTransgene(ProtectTest):
    def setUp(self):
        super(TestTransgene, self).setUp()
        test_dir = self._createTempDir()
        self.options = Job.Runner.getDefaultOptions(self._getTestJobStorePath())
        self.options.logLevel = 'INFO'
        self.options.workDir = test_dir
        self.options.clean = 'always'

    def test_transgene(self):
        """
        Test the functionality of run_transgene
        """
        univ_options = self._getTestUnivOptions()
        univ_options['output_folder'] = '/mnt/ephemeral/done'
        config_file = os.path.join(self._projectRootPath(),
                                   'src/protect/test/test_inputs/ci_parameters.yaml')
        test_src_folder = os.path.join(self._projectRootPath(), 'src', 'protect', 'test')
        a = Job.wrapJobFn(self._get_test_snpeff_file)
        b = Job.wrapJobFn(self._get_test_rna_bam)
        c = Job.wrapJobFn(self._get_all_tools, config_file).encapsulate()
        d = Job.wrapJobFn(self._get_tool, c.rv(), 'transgene')
        e = Job.wrapJobFn(run_transgene, a.rv(), b.rv(), univ_options, d.rv(), disk='100M',
                          memory='100M', cores=1).encapsulate()
        a.addChild(b)
        b.addChild(c)
        c.addChild(d)

        a.addChild(e)
        b.addChild(e)
        d.addChild(e)
        Job.Runner.startToil(a, self.options)

    @staticmethod
    def _get_all_tools(job, config_file):
        sample_set, univ_options, tool_options = _parse_config_file(job, config_file,
                                                                    max_cores=None)
        return tool_options

    @staticmethod
    def _get_tool(job, all_tools, tool):
        return all_tools[tool]

    @staticmethod
    def _get_test_snpeff_file(job):
        """
        Get the test snpeffed vcf file and write to jobstore

        :return: FSID for the snpeffed vcf file
        """
        base_call = 's3am download s3://cgl-pipeline-inputs/protect/unit_results/mutations/' \
                    'snpeffed/'
        filename = 'mutations.vcf'
        call = (base_call + ('%s.tar.gz ' % filename)*2).strip().split(' ')
        subprocess.check_call(call)
        untargz(filename + '.tar.gz', os.getcwd())
        return job.fileStore.writeGlobalFile(filename)

    @staticmethod
    def _get_test_rna_bam(job):
        """
        Get the test phlat file and write to jobstore

        :return: FSID for the phlat file
        """
        base_call = 's3am download s3://cgl-pipeline-inputs/protect/unit_results/alignments/'
        rna_files = {}
        for filename in ['rna_genome_sorted.bam', 'rna_genome_sorted.bam.bai']:
            call = (base_call + ('%s.tar.gz ' % filename) * 2).strip().split(' ')
            subprocess.check_call(call)
            untargz(filename + '.tar.gz', os.getcwd())
            rna_files[filename] = job.fileStore.writeGlobalFile(filename)
        return {'rna_genome': rna_files}

# noinspection PyProtectedMember
_get_all_tools = TestTransgene._get_all_tools
# noinspection PyProtectedMember
_get_tool = TestTransgene._get_tool
# noinspection PyProtectedMember
_get_test_snpeff_file = TestTransgene._get_test_snpeff_file
# noinspection PyProtectedMember
_get_test_rna_bam = TestTransgene._get_test_rna_bam