# Definitions
build_tool = runtime-container.DONE
name = quay.io/ucsc_cgl/protect
git_commit ?= db3301e89f3d3dcee5d16674b344bd090ca35b15
tag = 2.4.1--DOCKERVER--${git_commit}
short_tag = 2.4.1--DOCKERVER

build: Dockerfile
	docker build -t ${name}:${tag} .
	- docker rmi ${name}:${short_tag}
	- docker rmi ${name}:latest
	docker tag ${name}:${tag} ${name}:${short_tag}
	docker tag ${name}:${tag} ${name}:latest
	touch ${build_tool}

push: build
	# Requires ~/.dockercfg
	docker push ${name}:${tag}
	docker push ${name}:latest

clean:
	docker rmi -f ${name}:${tag}
	rm ${build_tool}